name: LStore Deploy

on:
  push:
    branches:
      - master  # دیپلوی روی تغییرات در برنچ مستر

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # دریافت کد پروژه

      - name: Check if SSH_PRIVATE_KEY is set
        run: |
          if [ -z "$SSH_PRIVATE_KEY" ]; then
            echo "SSH_PRIVATE_KEY is not set"
          else
            echo "SSH_PRIVATE_KEY is set"
          fi



      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # ساخت دایرکتوری .ssh
          mkdir -p ~/.ssh
          # ذخیره کلید خصوصی از GitHub Secrets در فایل id_rsa
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # اضافه کردن شناسه میزبان سرور به known_hosts برای جلوگیری از هشدارها
          ssh-keyscan -H "192.168.1.105" >> ~/.ssh/known_hosts
          # اتصال به سرور برای تست SSH و دریافت خروجی بیشتر
          ssh -i ~/.ssh/id_rsa matin@192.168.1.105 "echo 'SSH connection successful'"
          # انتقال فایل‌ها با rsync
          rsync -az --exclude='.git' --exclude='node_modules' . matin@192.168.1.105:/var/www/store/public_html
